import React,{useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Search,Globe2,ShieldCheck,Database,ExternalLink} from 'lucide-react';
import {advancedApi,intelApi} from '../api/modules';
import {PageHeader,GlassCard,Section,RiskBadge,LoadingState,ErrorState,EmptyState,DataTable} from '../components/ui';

export default function Intelligence(){
 const [sp]=useSearchParams();const [q,setQ]=useState(sp.get('q')||'');const [type,setType]=useState('search');const [data,setData]=useState(null),[busy,setBusy]=useState(false),[err,setErr]=useState(null);
 async function lookup(){if(!q.trim())return;setBusy(true);setErr(null);setData(null);try{let r;if(type==='ip')r=await intelApi.ip(q.trim());else if(type==='domain')r=await intelApi.domain(q.trim());else if(type==='url')r=await intelApi.url(q.trim());else r=await advancedApi.search(q.trim());setData(r.data)}catch(e){setErr(e)}finally{setBusy(false)}}
 return <><PageHeader eyebrow="THREAT INTELLIGENCE" title="Intelligence Lookup" subtitle="Search infrastructure and investigation data through the backend."/><div className="lookup"><select value={type} onChange={e=>setType(e.target.value)}><option value="search">Investigation Search</option><option value="ip">IP</option><option value="domain">Domain</option><option value="url">URL</option></select><div className="lookup-input"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&lookup()} placeholder="IP, domain, URL or investigation query"/></div><button className="primary" onClick={lookup}>Investigate</button></div>{busy?<LoadingState text="Querying threat intelligence…"/>:err?<ErrorState error={err}/>:data?<Results data={data} type={type}/>:<EmptyState title="Start an intelligence lookup" text="Enter an IP address, domain, URL, or investigation query."/>}</>
}
function Results({data,type}){
 const obj=data?.result||data;const geo=obj?.geolocation||obj?.geoip||obj?.geo||{};const rep=obj?.reputation||{};const rows=Array.isArray(obj?.items)?obj.items:Array.isArray(obj)?obj:[];
 if(type==='ip') return <div className="intel-grid"><Section title="IP Intelligence" subtitle="Approximate infrastructure context"><div className="intel-cards">{[['IP',obj?.ip],['Scope',obj?.ip_scope],['Country',geo.country||obj?.country],['Region',geo.subdivision],['City',geo.city||obj?.city],['ASN',geo.asn||obj?.asn],['Organization',geo.asn_organization||obj?.provider||obj?.asn_organization],['Latitude',geo.latitude],['Longitude',geo.longitude],['Reputation',typeof rep==='string'?rep:rep?.risk||rep?.status]].map(([k,v])=><GlassCard key={k}><span>{k}</span><strong>{v??'—'}</strong></GlassCard>)}</div><div className="notice">{geo.limitation||obj?.limitation||'IP geolocation is approximate infrastructure context and does not prove a person’s physical location.'}</div></Section></div>;
 return <div className="intel-grid"><Section title="Reputation & Context" subtitle="Backend-returned intelligence"><div className="intel-cards">{['reputation','country','city','asn','provider','confidence','risk'].map(k=><GlassCard key={k}><span>{k}</span><strong>{obj?.[k]??'—'}</strong></GlassCard>)}</div></Section><Section title="Related Indicators" subtitle="Returned records"><DataTable rows={rows} columns={[{key:'type',label:'Type'},{key:'value',label:'Value'},{key:'source',label:'Source'},{key:'risk',label:'Risk',render:r=><RiskBadge level={r.risk}/>} ,{key:'confidence',label:'Confidence'}]}/></Section></div>
}
